# Generated by Django 5.0 on 2023-12-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_tag_rename_created_task_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=13)),
                ('pass1', models.CharField(max_length=20)),
                ('pass2', models.CharField(max_length=20)),
            ],
        ),
    ]
