# Generated by Django 5.0 on 2023-12-28 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
