name: Python CI

on:
  push:
    branches:
      - master  # Change this to the default branch of your repository

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust based on your project structure and dependencies
    
    - name: Debug
      run: |
        ls -R
        ls -R api
    
    - name: Run unit tests
      run: |
        python -m unittest discover -s api -p 'tests.py'

    - name: Run integration tests
      run: |
        python -m unittest discover -s todo_app -p 'tests.py'

  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust based on your project structure and dependencies

    - name: Run Flake8
      run: |
        flake8

    - name: Run Black
      run: |
        black --check .
