name: Python CI

on:
  push:
    branches:
      - master  # Change this to the default branch of your repository

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run unit tests
      run: |
        python -m unittest discover -s algobulls_todo/api -p 'test_*.py'

    - name: Run integration tests
      run: |
        python -m unittest discover -s algobulls_todo/todo_app -p 'test_*.py'

  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust based on your project structure and dependencies

    - name: Auto-format with autopep8
      run: |
        pip install autopep8
        autopep8 --recursive --in-place --exclude=venv .

    - name: Run Flake8 
      run: |
        flake8

    - name: Auto-format with black
      run: |
        pip install black
        black .

    - name: Run Black
      run: |
        black --check .
